openapi: 3.0.0
info:
  title: Fraud Detection API
  version: 1.0.0
  description: Real-time fraud detection system for financial transactions
paths:
  /api/detect:
    post:
      summary: Detect fraudulent transactions
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                amount:
                  type: number
                time:
                  type: number
      responses:
        '200':
          description: Fraud detection result
  /api/stats:
    get:
      summary: Get fraud detection statistics
      responses:
        '200':
          description: System statistics